#
#
#
#
#
TREND_WEAK = 1
TREND_NORMAL = 2
TREND_STRONG = 3
TREND_VERY_STRONG = 4
#
TREND_WEAK_LABEL = "Weak"
TREND_NORMAL_LABEL = "Normal"
TREND_STRONG_LABEL = "Strong"
TREND_VERY_STRONG_LABEL = "Very Strong"
#
TREND_WEAK_MAX = 25
TREND_NORMAL_MAX = 50
TREND_STRONG_MAX = 75
#
LENGTH_SHORT_ADX = 10
LENGTH_LONG_ADX = 45
#
LENGTH_ATR = 14
#
TODAY_IS_UP = 1
TODAY_IS_DOWN = -1
TODAY_NO_MOVE = 0
#
TODAY_IS_UP_LABEL = "Up"
TODAY_IS_DOWN_LABEL = "Down"
TODAY_NO_MOVE_LABEL = "No change"
